use crate::inout::commandline::{OptArgType, OptCell};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum EProverOption {
    Help,
    Version,
    Verbose,
    Output,
    Silent,
    OutputLevel,
    PrintStatistics,
    PrintDetailedStatistics,
    PrintSaturated,
    PrintSatInfo,
    FilterSaturated,
    ProofObject,
    ProofGraph,
    ProofStatistics,
    FullDerivation,
    ForceDerivation,
    RecordGivenClauses,
    TrainingExamples,
    PclTermsCompressed,
    PclCompact,
    PclShellLevel,
    CpuLimit,
    SoftCpuLimit,
    MemoryLimit,
    ResourcesInfo,
    SelectStrategy,
    PrintStrategy,
    ParseStrategy,
    ProcessedClausesLimit,
    ProcessedSetLimit,
    UnprocessedLimit,
    TotalClauseSetLimit,
    GeneratedLimit,
    TermBankInsertLimit,
    Answers,
    ConjecturesAreQuestions,
    EqnNoInfix,
    FullEquationalRep,
    PrintOrientedEqLitsAsRules,
    LopIn,
    PclOut,
    TptpIn,
    TptpOut,
    TptpFormat,
    TstpIn,
    TstpOut,
    TstpFormat,
    SyntaxOnly,
    PrintFormulas,
    PruneOnly,
    CnfOnly,
    PrintPid,
    PrintVersion,
    RequireNonempty,
    Auto,
    AutoSchedule,
    SerializeSchedule,
    ForcePreprocessingSchedule,
    SatAutoSchedule,
    NoPreprocessing,
    EqUnfoldLimit,
    EqUnfoldMaxClauses,
    NoEqUnfolding,
    GoalDefs,
    GoalSubtermDefs,
    Sine,
    RelPruningLevel,
    PresatSimplify,
    AcHandling,
    AcNonAggressive,
    LiteralSelectionStrategy,
    NoGeneration,
    SelectOnProcessingOnly,
    InheritParamodLiterals,
    InheritGoalParamodLiterals,
    InheritConjectureParamodLiterals,
    SelectionPosMin,
    SelectionPosMax,
    SelectionNegMin,
    SelectionNegMax,
    SelectionAllMin,
    SelectionAllMax,
    SelectionWeightMin,
    PreferInitialClauses,
    ExpertHeuristic,
    FilterOrphansLimit,
    ForwardContractLimit,
    DeleteBadLimit,
    AssumeCompleteness,
    AssumeIncompleteness,
    DisableEqFactoring,
    DisableParamodIntoNegUnits,
    Condense,
    CondenseAggressive,
    DisableGivenClauseForwardContraction,
    SimulParamod,
    OrientedSimulParamod,
    SupersimulParamod,
    OrientedSupersimulParamod,
    SplitClauses,
    SplitMethod,
    SplitAggressive,
    SplitReuseDefs,
    DisequalityDecomposition,
    DisequalityDecompMaxArity,
    SosUsesInputTypes,
    DestructiveEr,
    StrongDestructiveEr,
    DestructiveErAggressive,
    ForwardContextSr,
    ForwardContextSrAggressive,
    BackwardContextSr,
    PreferGeneralDemodulators,
    ForwardDemodLevel,
    DemodUnderLambda,
    StrongRwInst,
    StrongForwardSubsumption,
    SatCheckProcInterval,
    SatCheckGenInterval,
    SatCheckTTInsertInterval,
    SatCheck,
    SatCheckDecisionLimit,
    SatCheckNormalizeConst,
    SatCheckNormalizeUnproc,
    LiftLambdas,
    Watchlist,
    StaticWatchlist,
    NoWatchlistSimplification,
    ForwardSubsumptionAggressive,
    ConventionalSubsumption,
    SubsumptionIndexing,
    FvIndexFeatureTypes,
    FvIndexMaxFeatures,
    FvIndexSlack,
    RewriteBackwardIndex,
    ParamodFromIndex,
    ParamodIntoIndex,
    FingerprintIndex,
    FingerprintNoSizeConstr,
    PdtNoSizeConstr,
    PdtNoAgeConstr,
    DefineWeightFunction,
    DefineHeuristic,
    FreeNumbers,
    FreeObjects,
    DefinitionalCnf,
    FoolUnroll,
    MiniscopeLimit,
    PrintTypes,
    AppEncode,
    ArgCong,
    NegExt,
    PosExt,
    ExtSupMaxDepth,
    InverseRecognition,
    ReplaceInjDefs,
    Bce,
    BceMaxOccs,
    PredElim,
    PredElimRecognizeGates,
    PredElimForceMuDecrease,
    PredElimIgnoreConjSyms,
    PredElimMaxOccs,
    PredElimTolerance,
    CnfLambdaToForall,
    EtaNormalize,
    HoOrderKind,
    EliminateLeibnizEq,
    UnrollFormulasOnly,
    PrimEnumMode,
    PrimEnumMaxDepth,
    InstChoiceMaxDepth,
    LocalRw,
    PruneArgs,
    FuncProjLimit,
    ImitLimit,
    IdentLimit,
    ElimLimit,
    UnifMode,
    PatternOracle,
    FixpointOracle,
    MaxUnifiers,
    MaxUnifSteps,
    ClassificationTimeoutPortion,
    PreinstantiateInduction,
    TermOrdering,
    OrderWeightGeneration,
    OrderWeights,
    OrderPrecedenceGeneration,
    PrecPureConj,
    PrecConjAxiom,
    PrecPureAxiom,
    PrecSkolem,
    PrecDefPred,
    OrderConstantWeight,
    Precedence,
    LpoRecursionLimit,
    RestrictLiteralComparisons,
    LiteralComparison,
    KboLambdaWeight,
    KboDbWeight,
    DeterministicRewriteSort,
    DeterministicNewSort,
}

pub const EPROVER_OPTIONS: &[OptCell<EProverOption>] = &[
    OptCell::new(
        EProverOption::Help,
        Some('h'),
        Some("help"),
        OptArgType::NoArg,
        None,
        "Print a short description of program usage and options.",
    ),
    OptCell::new(
        EProverOption::Version,
        Some('V'),
        Some("version"),
        OptArgType::NoArg,
        None,
        "Print the version number of the prover. Please include this with all bug reports (if any).",
    ),
    OptCell::new(
        EProverOption::Verbose,
        Some('v'),
        Some("verbose"),
        OptArgType::OptArg,
        Some("1"),
        "Verbose comments on the progress of the program.",
    ),
    OptCell::new(
        EProverOption::Output,
        Some('o'),
        Some("output-file"),
        OptArgType::ReqArg,
        None,
        "Redirect output into the named file.",
    ),
    OptCell::new(
        EProverOption::Silent,
        Some('s'),
        Some("silent"),
        OptArgType::NoArg,
        None,
        "Equivalent to --output-level=0.",
    ),
    OptCell::new(
        EProverOption::OutputLevel,
        Some('l'),
        Some("output-level"),
        OptArgType::ReqArg,
        None,
        "Select an output level, greater values imply more verbose output.",
    ),
    OptCell::new(
        EProverOption::PrintStatistics,
        None,
        Some("print-statistics"),
        OptArgType::NoArg,
        None,
        "Print inference statistics.",
    ),
    OptCell::new(
        EProverOption::PrintDetailedStatistics,
        Some('0'),
        Some("print-detailed-statistics"),
        OptArgType::NoArg,
        None,
        "Print potentially expensive proof-state statistics.",
    ),
    OptCell::new(
        EProverOption::PrintSaturated,
        Some('S'),
        Some("print-saturated"),
        OptArgType::OptArg,
        Some("eigEIG"),
        "Print the saturated clause sets after termination.",
    ),
    OptCell::new(
        EProverOption::PrintSatInfo,
        None,
        Some("print-sat-info"),
        OptArgType::NoArg,
        None,
        "Print additional clause information in saturated output.",
    ),
    OptCell::new(
        EProverOption::FilterSaturated,
        None,
        Some("filter-saturated"),
        OptArgType::OptArg,
        Some("Fc"),
        "Filter the saturated clause sets after termination.",
    ),
    OptCell::new(
        EProverOption::ProofObject,
        Some('p'),
        Some("proof-object"),
        OptArgType::OptArg,
        Some("1"),
        "Generate and print an internal proof object in case of success.",
    ),
    OptCell::new(
        EProverOption::ProofGraph,
        None,
        Some("proof-graph"),
        OptArgType::OptArg,
        Some("3"),
        "Generate an internal proof object as a GraphViz dot graph in case of success.",
    ),
    OptCell::new(
        EProverOption::ProofStatistics,
        None,
        Some("proof-statistics"),
        OptArgType::NoArg,
        None,
        "Print various statistics of the proof object.",
    ),
    OptCell::new(
        EProverOption::FullDerivation,
        Some('d'),
        Some("full-deriv"),
        OptArgType::NoArg,
        None,
        "Include all derived formulas and clauses in the proof object.",
    ),
    OptCell::new(
        EProverOption::ForceDerivation,
        None,
        Some("force-deriv"),
        OptArgType::OptArg,
        Some("1"),
        "Force output of the derivation in indeterminate cases.",
    ),
    OptCell::new(
        EProverOption::RecordGivenClauses,
        None,
        Some("record-gcs"),
        OptArgType::NoArg,
        None,
        "Record given-clause selection as separate pseudo-inferences.",
    ),
    OptCell::new(
        EProverOption::TrainingExamples,
        None,
        Some("training-examples"),
        OptArgType::OptArg,
        Some("1"),
        "Generate and process training examples from the proof-search object.",
    ),
    OptCell::new(
        EProverOption::PclTermsCompressed,
        None,
        Some("pcl-terms-compressed"),
        OptArgType::NoArg,
        None,
        "Print terms in the PCL output in shared representation.",
    ),
    OptCell::new(
        EProverOption::PclCompact,
        None,
        Some("pcl-compact"),
        OptArgType::NoArg,
        None,
        "Print PCL steps without additional spaces for formatting.",
    ),
    OptCell::new(
        EProverOption::PclShellLevel,
        None,
        Some("pcl-shell-level"),
        OptArgType::OptArg,
        Some("1"),
        "Set the level to which clauses and formulas are suppressed in proof output.",
    ),
    OptCell::new(
        EProverOption::MemoryLimit,
        Some('m'),
        Some("memory-limit"),
        OptArgType::ReqArg,
        None,
        "Limit the memory the prover may use. The argument is the allowed amount of memory in MB.",
    ),
    OptCell::new(
        EProverOption::CpuLimit,
        None,
        Some("cpu-limit"),
        OptArgType::OptArg,
        Some("300"),
        "Limit the per-core CPU time the prover should run.",
    ),
    OptCell::new(
        EProverOption::SoftCpuLimit,
        None,
        Some("soft-cpu-limit"),
        OptArgType::OptArg,
        Some("290"),
        "Limit the CPU time the prover should spend in the main saturation phase.",
    ),
    OptCell::new(
        EProverOption::ResourcesInfo,
        Some('R'),
        Some("resources-info"),
        OptArgType::NoArg,
        None,
        "Give information about resources used by the prover.",
    ),
    OptCell::new(
        EProverOption::SelectStrategy,
        None,
        Some("select-strategy"),
        OptArgType::ReqArg,
        None,
        "Select one of the built-in strategies.",
    ),
    OptCell::new(
        EProverOption::PrintStrategy,
        None,
        Some("print-strategy"),
        OptArgType::OptArg,
        Some(">current-strategy<"),
        "Print a representation of search parameters for a strategy.",
    ),
    OptCell::new(
        EProverOption::ParseStrategy,
        None,
        Some("parse-strategy"),
        OptArgType::ReqArg,
        None,
        "Parse a printed strategy representation.",
    ),
    OptCell::new(
        EProverOption::ProcessedClausesLimit,
        Some('C'),
        Some("processed-clauses-limit"),
        OptArgType::ReqArg,
        None,
        "Set the maximal number of clauses to process.",
    ),
    OptCell::new(
        EProverOption::ProcessedSetLimit,
        Some('P'),
        Some("processed-set-limit"),
        OptArgType::ReqArg,
        None,
        "Set the maximal size of the processed set.",
    ),
    OptCell::new(
        EProverOption::UnprocessedLimit,
        Some('U'),
        Some("unprocessed-limit"),
        OptArgType::ReqArg,
        None,
        "Set the maximal size of the unprocessed set.",
    ),
    OptCell::new(
        EProverOption::TotalClauseSetLimit,
        Some('T'),
        Some("total-clause-set-limit"),
        OptArgType::ReqArg,
        None,
        "Set the maximal size of all clause sets.",
    ),
    OptCell::new(
        EProverOption::GeneratedLimit,
        None,
        Some("generated-limit"),
        OptArgType::ReqArg,
        None,
        "Set the maximal number of generated clauses.",
    ),
    OptCell::new(
        EProverOption::TermBankInsertLimit,
        None,
        Some("tb-insert-limit"),
        OptArgType::ReqArg,
        None,
        "Set the maximal number of term-bank top insertions.",
    ),
    OptCell::new(
        EProverOption::Answers,
        None,
        Some("answers"),
        OptArgType::OptArg,
        Some("2147483647"),
        "Set the maximal number of answers for existential questions.",
    ),
    OptCell::new(
        EProverOption::ConjecturesAreQuestions,
        None,
        Some("conjectures-are-questions"),
        OptArgType::NoArg,
        None,
        "Treat all conjectures as questions to be answered.",
    ),
    OptCell::new(
        EProverOption::EqnNoInfix,
        Some('n'),
        Some("eqn-no-infix"),
        OptArgType::NoArg,
        None,
        "In LOP, print equations in prefix notation.",
    ),
    OptCell::new(
        EProverOption::FullEquationalRep,
        Some('e'),
        Some("full-equational-rep"),
        OptArgType::NoArg,
        None,
        "In LOP, print all literals as equations.",
    ),
    OptCell::new(
        EProverOption::PrintOrientedEqLitsAsRules,
        None,
        Some("print-oriented-eqlits-as-rules"),
        OptArgType::NoArg,
        None,
        "Print oriented equational literals as rules.",
    ),
    OptCell::new(
        EProverOption::LopIn,
        None,
        Some("lop-in"),
        OptArgType::NoArg,
        None,
        "Set E-LOP as the input format.",
    ),
    OptCell::new(
        EProverOption::PclOut,
        None,
        Some("pcl-out"),
        OptArgType::NoArg,
        None,
        "Set PCL as the proof-object output format.",
    ),
    OptCell::new(
        EProverOption::TptpIn,
        None,
        Some("tptp-in"),
        OptArgType::NoArg,
        None,
        "Set TPTP-2 as the input format.",
    ),
    OptCell::new(
        EProverOption::TptpOut,
        None,
        Some("tptp-out"),
        OptArgType::NoArg,
        None,
        "Print TPTP format instead of E-LOP.",
    ),
    OptCell::new(
        EProverOption::TptpFormat,
        None,
        Some("tptp-format"),
        OptArgType::NoArg,
        None,
        "Equivalent to --tptp-in and --tptp-out.",
    ),
    OptCell::new(
        EProverOption::TptpIn,
        None,
        Some("tptp2-in"),
        OptArgType::NoArg,
        None,
        "Synonymous with --tptp-in.",
    ),
    OptCell::new(
        EProverOption::TptpOut,
        None,
        Some("tptp2-out"),
        OptArgType::NoArg,
        None,
        "Synonymous with --tptp-out.",
    ),
    OptCell::new(
        EProverOption::TptpFormat,
        None,
        Some("tptp2-format"),
        OptArgType::NoArg,
        None,
        "Synonymous with --tptp-format.",
    ),
    OptCell::new(
        EProverOption::TstpIn,
        None,
        Some("tstp-in"),
        OptArgType::NoArg,
        None,
        "Set TPTP-3 as the input format.",
    ),
    OptCell::new(
        EProverOption::TstpOut,
        None,
        Some("tstp-out"),
        OptArgType::NoArg,
        None,
        "Print output clauses in TPTP-3 syntax.",
    ),
    OptCell::new(
        EProverOption::TstpFormat,
        None,
        Some("tstp-format"),
        OptArgType::NoArg,
        None,
        "Equivalent to --tstp-in and --tstp-out.",
    ),
    OptCell::new(
        EProverOption::TstpIn,
        None,
        Some("tptp3-in"),
        OptArgType::NoArg,
        None,
        "Synonymous with --tstp-in.",
    ),
    OptCell::new(
        EProverOption::TstpOut,
        None,
        Some("tptp3-out"),
        OptArgType::NoArg,
        None,
        "Synonymous with --tstp-out.",
    ),
    OptCell::new(
        EProverOption::TstpFormat,
        None,
        Some("tptp3-format"),
        OptArgType::NoArg,
        None,
        "Synonymous with --tstp-format.",
    ),
    OptCell::new(
        EProverOption::SyntaxOnly,
        None,
        Some("syntax-only"),
        OptArgType::NoArg,
        None,
        "Stop after parsing, i.e. only check if the input can be parsed correctly.",
    ),
    OptCell::new(
        EProverOption::PrintFormulas,
        None,
        Some("print-formulas"),
        OptArgType::NoArg,
        None,
        "Print back an include-expanded formula-version of the problem after syntax checking.",
    ),
    OptCell::new(
        EProverOption::PruneOnly,
        None,
        Some("prune"),
        OptArgType::NoArg,
        None,
        "Stop after relevancy pruning and output the initial clause and formula set.",
    ),
    OptCell::new(
        EProverOption::CnfOnly,
        None,
        Some("cnf"),
        OptArgType::NoArg,
        None,
        "Convert the input problem into clause normal form and print it.",
    ),
    OptCell::new(
        EProverOption::PrintPid,
        None,
        Some("print-pid"),
        OptArgType::NoArg,
        None,
        "Print the process id of the prover as a comment after option processing.",
    ),
    OptCell::new(
        EProverOption::PrintVersion,
        None,
        Some("print-version"),
        OptArgType::NoArg,
        None,
        "Print the version number of the prover as a comment after option processing.",
    ),
    OptCell::new(
        EProverOption::RequireNonempty,
        None,
        Some("error-on-empty"),
        OptArgType::NoArg,
        None,
        "Return with an error code if the input file contains no clauses.",
    ),
    OptCell::new(
        EProverOption::Auto,
        None,
        Some("auto"),
        OptArgType::NoArg,
        None,
        "Automatically determine settings for proof search.",
    ),
    OptCell::new(
        EProverOption::AutoSchedule,
        None,
        Some("auto-schedule"),
        OptArgType::OptArg,
        Some("1"),
        "Use strategy scheduling and set the number of schedule cores.",
    ),
    OptCell::new(
        EProverOption::ForcePreprocessingSchedule,
        None,
        Some("force-preproc-sched"),
        OptArgType::ReqArg,
        None,
        "Force preprocessing schedule insertion when autoscheduling is used.",
    ),
    OptCell::new(
        EProverOption::SerializeSchedule,
        None,
        Some("serialize-schedule"),
        OptArgType::ReqArg,
        None,
        "Convert parallel auto-schedule into serialized one.",
    ),
    OptCell::new(
        EProverOption::SatAutoSchedule,
        None,
        Some("satauto-schedule"),
        OptArgType::OptArg,
        Some("1"),
        "Use strategy scheduling without SInE.",
    ),
    OptCell::new(
        EProverOption::NoPreprocessing,
        None,
        Some("no-preprocessing"),
        OptArgType::NoArg,
        None,
        "Disable preprocessing.",
    ),
    OptCell::new(
        EProverOption::EqUnfoldLimit,
        None,
        Some("eq-unfold-limit"),
        OptArgType::ReqArg,
        None,
        "Set the incremental limit for equation definition unfolding.",
    ),
    OptCell::new(
        EProverOption::EqUnfoldMaxClauses,
        None,
        Some("eq-unfold-maxclauses"),
        OptArgType::ReqArg,
        None,
        "Set the maximal number of clauses for equation definition unfolding.",
    ),
    OptCell::new(
        EProverOption::NoEqUnfolding,
        None,
        Some("no-eq-unfolding"),
        OptArgType::NoArg,
        None,
        "Disable equation definition unfolding.",
    ),
    OptCell::new(
        EProverOption::GoalDefs,
        None,
        Some("goal-defs"),
        OptArgType::OptArg,
        Some("All"),
        "Introduce goal definitions.",
    ),
    OptCell::new(
        EProverOption::GoalSubtermDefs,
        None,
        Some("goal-subterm-defs"),
        OptArgType::NoArg,
        None,
        "Introduce goal definitions for subterms.",
    ),
    OptCell::new(
        EProverOption::Sine,
        None,
        Some("sine"),
        OptArgType::OptArg,
        Some("Auto"),
        "Select a SInE axiom-selection strategy.",
    ),
    OptCell::new(
        EProverOption::RelPruningLevel,
        None,
        Some("rel-pruning-level"),
        OptArgType::OptArg,
        Some("3"),
        "Select the relevance pruning level.",
    ),
    OptCell::new(
        EProverOption::PresatSimplify,
        None,
        Some("presat-simplify"),
        OptArgType::OptArg,
        Some("true"),
        "Run presaturation interreduction.",
    ),
    OptCell::new(
        EProverOption::AcHandling,
        None,
        Some("ac-handling"),
        OptArgType::OptArg,
        Some("KeepUnits"),
        "Select handling of associativity and commutativity axioms.",
    ),
    OptCell::new(
        EProverOption::AcNonAggressive,
        None,
        Some("ac-non-aggressive"),
        OptArgType::NoArg,
        None,
        "Disable aggressive AC resolution processing.",
    ),
    OptCell::new(
        EProverOption::LiteralSelectionStrategy,
        Some('W'),
        Some("literal-selection-strategy"),
        OptArgType::ReqArg,
        None,
        "Choose a negative literal-selection strategy.",
    ),
    OptCell::new(
        EProverOption::NoGeneration,
        None,
        Some("no-generation"),
        OptArgType::NoArg,
        None,
        "Inhibit all generating inferences.",
    ),
    OptCell::new(
        EProverOption::SelectOnProcessingOnly,
        None,
        Some("select-on-processing-only"),
        OptArgType::NoArg,
        None,
        "Perform literal selection only on the given clause.",
    ),
    OptCell::new(
        EProverOption::InheritParamodLiterals,
        Some('i'),
        Some("inherit-paramod-literals"),
        OptArgType::NoArg,
        None,
        "Inherit negative literals previously paramodulated into.",
    ),
    OptCell::new(
        EProverOption::InheritGoalParamodLiterals,
        Some('j'),
        Some("inherit-goal-pm-literals"),
        OptArgType::NoArg,
        None,
        "Inherit previous paramodulation literals in goal clauses.",
    ),
    OptCell::new(
        EProverOption::InheritConjectureParamodLiterals,
        None,
        Some("inherit-conjecture-pm-literals"),
        OptArgType::NoArg,
        None,
        "Inherit previous paramodulation literals in conjecture-derived clauses.",
    ),
    OptCell::new(
        EProverOption::SelectionPosMin,
        None,
        Some("selection-pos-min"),
        OptArgType::ReqArg,
        None,
        "Set the minimum positive-literal count for literal selection.",
    ),
    OptCell::new(
        EProverOption::SelectionPosMax,
        None,
        Some("selection-pos-max"),
        OptArgType::ReqArg,
        None,
        "Set the maximum positive-literal count for literal selection.",
    ),
    OptCell::new(
        EProverOption::SelectionNegMin,
        None,
        Some("selection-neg-min"),
        OptArgType::ReqArg,
        None,
        "Set the minimum negative-literal count for literal selection.",
    ),
    OptCell::new(
        EProverOption::SelectionNegMax,
        None,
        Some("selection-neg-max"),
        OptArgType::ReqArg,
        None,
        "Set the maximum negative-literal count for literal selection.",
    ),
    OptCell::new(
        EProverOption::SelectionAllMin,
        None,
        Some("selection-all-min"),
        OptArgType::ReqArg,
        None,
        "Set the minimum total literal count for literal selection.",
    ),
    OptCell::new(
        EProverOption::SelectionAllMax,
        None,
        Some("selection-all-max"),
        OptArgType::ReqArg,
        None,
        "Set the maximum total literal count for literal selection.",
    ),
    OptCell::new(
        EProverOption::SelectionWeightMin,
        None,
        Some("selection-weight-min"),
        OptArgType::ReqArg,
        None,
        "Set the minimum clause weight for literal selection.",
    ),
    OptCell::new(
        EProverOption::PreferInitialClauses,
        None,
        Some("prefer-initial-clauses"),
        OptArgType::NoArg,
        None,
        "Always process all initial clauses first.",
    ),
    OptCell::new(
        EProverOption::ExpertHeuristic,
        Some('x'),
        Some("expert-heuristic"),
        OptArgType::ReqArg,
        None,
        "Select a clause-selection heuristic.",
    ),
    OptCell::new(
        EProverOption::FilterOrphansLimit,
        None,
        Some("filter-orphans-limit"),
        OptArgType::OptArg,
        Some("100"),
        "Set eager orphan-filtering limit.",
    ),
    OptCell::new(
        EProverOption::ForwardContractLimit,
        None,
        Some("forward-contract-limit"),
        OptArgType::OptArg,
        Some("80000"),
        "Set forward-contraction refresh limit.",
    ),
    OptCell::new(
        EProverOption::DeleteBadLimit,
        None,
        Some("delete-bad-limit"),
        OptArgType::OptArg,
        Some("1500000"),
        "Set storage-unit limit for deleting bad clauses.",
    ),
    OptCell::new(
        EProverOption::AssumeCompleteness,
        None,
        Some("assume-completeness"),
        OptArgType::NoArg,
        None,
        "Assume the selected inference system is complete.",
    ),
    OptCell::new(
        EProverOption::AssumeIncompleteness,
        None,
        Some("assume-incompleteness"),
        OptArgType::NoArg,
        None,
        "Assume the selected configuration is incomplete.",
    ),
    OptCell::new(
        EProverOption::DisableEqFactoring,
        None,
        Some("disable-eq-factoring"),
        OptArgType::NoArg,
        None,
        "Disable equality factoring.",
    ),
    OptCell::new(
        EProverOption::DisableParamodIntoNegUnits,
        None,
        Some("disable-paramod-into-neg-units"),
        OptArgType::NoArg,
        None,
        "Disable paramodulation into negative unit clauses.",
    ),
    OptCell::new(
        EProverOption::Condense,
        None,
        Some("condense"),
        OptArgType::NoArg,
        None,
        "Enable condensing for the given clause.",
    ),
    OptCell::new(
        EProverOption::CondenseAggressive,
        None,
        Some("condense-aggressive"),
        OptArgType::NoArg,
        None,
        "Enable condensing for given and newly generated clauses.",
    ),
    OptCell::new(
        EProverOption::DisableGivenClauseForwardContraction,
        None,
        Some("disable-given-clause-fw-contraction"),
        OptArgType::NoArg,
        None,
        "Disable simplification and subsumption of the selected given clause.",
    ),
    OptCell::new(
        EProverOption::SimulParamod,
        None,
        Some("simul-paramod"),
        OptArgType::NoArg,
        None,
        "Use simultaneous paramodulation.",
    ),
    OptCell::new(
        EProverOption::OrientedSimulParamod,
        None,
        Some("oriented-simul-paramod"),
        OptArgType::NoArg,
        None,
        "Use simultaneous paramodulation for oriented from-literals.",
    ),
    OptCell::new(
        EProverOption::SupersimulParamod,
        None,
        Some("supersimul-paramod"),
        OptArgType::NoArg,
        None,
        "Use supersimultaneous paramodulation.",
    ),
    OptCell::new(
        EProverOption::OrientedSupersimulParamod,
        None,
        Some("oriented-supersimul-paramod"),
        OptArgType::NoArg,
        None,
        "Use supersimultaneous paramodulation for oriented from-literals.",
    ),
    OptCell::new(
        EProverOption::SplitClauses,
        None,
        Some("split-clauses"),
        OptArgType::OptArg,
        Some("7"),
        "Determine which clause classes should be split.",
    ),
    OptCell::new(
        EProverOption::SplitMethod,
        None,
        Some("split-method"),
        OptArgType::ReqArg,
        None,
        "Determine how to treat ground literals in splitting.",
    ),
    OptCell::new(
        EProverOption::SplitAggressive,
        None,
        Some("split-aggressive"),
        OptArgType::NoArg,
        None,
        "Apply splitting to newly generated clauses.",
    ),
    OptCell::new(
        EProverOption::SplitReuseDefs,
        None,
        Some("split-reuse-defs"),
        OptArgType::NoArg,
        None,
        "Reuse previous splitting definitions when possible.",
    ),
    OptCell::new(
        EProverOption::DisequalityDecomposition,
        None,
        Some("disequality-decomposition"),
        OptArgType::OptArg,
        Some("1024"),
        "Enable disequality decomposition.",
    ),
    OptCell::new(
        EProverOption::DisequalityDecompMaxArity,
        None,
        Some("disequality-decomp-maxarity"),
        OptArgType::OptArg,
        Some("1"),
        "Limit disequality decomposition by function-symbol arity.",
    ),
    OptCell::new(
        EProverOption::SosUsesInputTypes,
        None,
        Some("sos-uses-input-types"),
        OptArgType::NoArg,
        None,
        "Use TPTP input roles when initializing the set of support.",
    ),
    OptCell::new(
        EProverOption::DestructiveEr,
        None,
        Some("destructive-er"),
        OptArgType::NoArg,
        None,
        "Enable destructive equality resolution on pure-variable disequalities.",
    ),
    OptCell::new(
        EProverOption::StrongDestructiveEr,
        None,
        Some("strong-destructive-er"),
        OptArgType::NoArg,
        None,
        "Enable destructive equality resolution on X != t disequalities.",
    ),
    OptCell::new(
        EProverOption::DestructiveErAggressive,
        None,
        Some("destructive-er-aggressive"),
        OptArgType::NoArg,
        None,
        "Apply destructive equality resolution to newly generated clauses.",
    ),
    OptCell::new(
        EProverOption::ForwardContextSr,
        None,
        Some("forward-context-sr"),
        OptArgType::NoArg,
        None,
        "Apply contextual simplify-reflect with processed clauses to the given clause.",
    ),
    OptCell::new(
        EProverOption::ForwardContextSrAggressive,
        None,
        Some("forward-context-sr-aggressive"),
        OptArgType::NoArg,
        None,
        "Apply contextual simplify-reflect with processed clauses to new clauses.",
    ),
    OptCell::new(
        EProverOption::BackwardContextSr,
        None,
        Some("backward-context-sr"),
        OptArgType::NoArg,
        None,
        "Apply contextual simplify-reflect from the given clause to processed clauses.",
    ),
    OptCell::new(
        EProverOption::PreferGeneralDemodulators,
        Some('g'),
        Some("prefer-general-demodulators"),
        OptArgType::NoArg,
        None,
        "Prefer general demodulators when traversing rewrite indexes.",
    ),
    OptCell::new(
        EProverOption::ForwardDemodLevel,
        Some('F'),
        Some("forward-demod-level"),
        OptArgType::ReqArg,
        None,
        "Set forward demodulation level: 0 none, 1 rules, 2 full rewriting.",
    ),
    OptCell::new(
        EProverOption::DemodUnderLambda,
        None,
        Some("demod-under-lambda"),
        OptArgType::ReqArg,
        None,
        "Demodulate closed subterms under lambdas.",
    ),
    OptCell::new(
        EProverOption::StrongRwInst,
        None,
        Some("strong-rw-inst"),
        OptArgType::NoArg,
        None,
        "Instantiate unbound variables in matching potential demodulators.",
    ),
    OptCell::new(
        EProverOption::StrongForwardSubsumption,
        Some('u'),
        Some("strong-forward-subsumption"),
        OptArgType::NoArg,
        None,
        "Try multiple positions and unit equations for equational subsumption.",
    ),
    OptCell::new(
        EProverOption::SatCheckProcInterval,
        None,
        Some("satcheck-proc-interval"),
        OptArgType::OptArg,
        Some("5000"),
        "Enable periodic SAT checking by processed-clause interval.",
    ),
    OptCell::new(
        EProverOption::SatCheckGenInterval,
        None,
        Some("satcheck-gen-interval"),
        OptArgType::OptArg,
        Some("10000"),
        "Enable periodic SAT checking by proof-state size increase.",
    ),
    OptCell::new(
        EProverOption::SatCheckTTInsertInterval,
        None,
        Some("satcheck-ttinsert-interval"),
        OptArgType::OptArg,
        Some("5000000"),
        "Enable periodic SAT checking by term-top insertion interval.",
    ),
    OptCell::new(
        EProverOption::SatCheck,
        None,
        Some("satcheck"),
        OptArgType::OptArg,
        Some("FirstConst"),
        "Set the grounding strategy for periodic SAT checking.",
    ),
    OptCell::new(
        EProverOption::SatCheckDecisionLimit,
        None,
        Some("satcheck-decision-limit"),
        OptArgType::OptArg,
        Some("100"),
        "Set the SAT-solver decision limit for each SAT-check run.",
    ),
    OptCell::new(
        EProverOption::SatCheckNormalizeConst,
        None,
        Some("satcheck-normalize-const"),
        OptArgType::NoArg,
        None,
        "Use the selected constant's current normal form for SAT-check grounding.",
    ),
    OptCell::new(
        EProverOption::SatCheckNormalizeUnproc,
        None,
        Some("satcheck-normalize-unproc"),
        OptArgType::NoArg,
        None,
        "Re-simplify unprocessed clauses before SAT-check grounding.",
    ),
    OptCell::new(
        EProverOption::LiftLambdas,
        None,
        Some("lift-lambdas"),
        OptArgType::ReqArg,
        None,
        "Replace lambdas by named functions.",
    ),
    OptCell::new(
        EProverOption::Watchlist,
        None,
        Some("watchlist"),
        OptArgType::OptArg,
        Some("'Use inline watchlist type'"),
        "Use a file or inline TPTP watchlist clauses during saturation.",
    ),
    OptCell::new(
        EProverOption::StaticWatchlist,
        None,
        Some("static-watchlist"),
        OptArgType::OptArg,
        Some("'Use inline watchlist type'"),
        "Use a watchlist without removing subsumed watchlist clauses.",
    ),
    OptCell::new(
        EProverOption::NoWatchlistSimplification,
        None,
        Some("no-watchlist-simplification"),
        OptArgType::NoArg,
        None,
        "Disable simplification of watchlist clauses.",
    ),
    OptCell::new(
        EProverOption::ForwardSubsumptionAggressive,
        None,
        Some("fw-subsumption-aggressive"),
        OptArgType::NoArg,
        None,
        "Run forward subsumption on newly generated clauses before evaluation.",
    ),
    OptCell::new(
        EProverOption::ConventionalSubsumption,
        None,
        Some("conventional-subsumption"),
        OptArgType::NoArg,
        None,
        "Disable feature-vector subsumption indexing.",
    ),
    OptCell::new(
        EProverOption::SubsumptionIndexing,
        None,
        Some("subsumption-indexing"),
        OptArgType::ReqArg,
        None,
        "Select the subsumption indexing style.",
    ),
    OptCell::new(
        EProverOption::FvIndexFeatureTypes,
        None,
        Some("fvindex-featuretypes"),
        OptArgType::ReqArg,
        None,
        "Select feature types used for feature-vector indexing.",
    ),
    OptCell::new(
        EProverOption::FvIndexMaxFeatures,
        None,
        Some("fvindex-maxfeatures"),
        OptArgType::OptArg,
        Some("200"),
        "Set the maximum initial symbol count for feature-vector indexing.",
    ),
    OptCell::new(
        EProverOption::FvIndexSlack,
        None,
        Some("fvindex-slack"),
        OptArgType::OptArg,
        Some("0"),
        "Reserve feature-vector index slots for symbols introduced later.",
    ),
    OptCell::new(
        EProverOption::RewriteBackwardIndex,
        None,
        Some("rw-bw-index"),
        OptArgType::OptArg,
        Some("FP7"),
        "Select the fingerprint function for the backwards rewrite index.",
    ),
    OptCell::new(
        EProverOption::ParamodFromIndex,
        None,
        Some("pm-from-index"),
        OptArgType::OptArg,
        Some("FP7"),
        "Select the fingerprint function for paramodulation-from indexing.",
    ),
    OptCell::new(
        EProverOption::ParamodIntoIndex,
        None,
        Some("pm-into-index"),
        OptArgType::OptArg,
        Some("FP7"),
        "Select the fingerprint function for paramodulation-into indexing.",
    ),
    OptCell::new(
        EProverOption::FingerprintIndex,
        None,
        Some("fp-index"),
        OptArgType::OptArg,
        Some("FP7"),
        "Select the fingerprint function for all fingerprint indices.",
    ),
    OptCell::new(
        EProverOption::FingerprintNoSizeConstr,
        None,
        Some("fp-no-size-constr"),
        OptArgType::NoArg,
        None,
        "Advertised by the C option table, but not handled by the C option switch.",
    ),
    OptCell::new(
        EProverOption::PdtNoSizeConstr,
        None,
        Some("pdt-no-size-constr"),
        OptArgType::NoArg,
        None,
        "Disable size constraints for perfect-discrimination-tree indexing.",
    ),
    OptCell::new(
        EProverOption::PdtNoAgeConstr,
        None,
        Some("pdt-no-age-constr"),
        OptArgType::NoArg,
        None,
        "Disable age constraints for perfect-discrimination-tree indexing.",
    ),
    OptCell::new(
        EProverOption::DefineWeightFunction,
        Some('D'),
        Some("define-weight-function"),
        OptArgType::ReqArg,
        None,
        "Define a weight function for clause selection.",
    ),
    OptCell::new(
        EProverOption::DefineHeuristic,
        Some('H'),
        Some("define-heuristic"),
        OptArgType::ReqArg,
        None,
        "Define a clause-selection heuristic.",
    ),
    OptCell::new(
        EProverOption::FreeNumbers,
        None,
        Some("free-numbers"),
        OptArgType::NoArg,
        None,
        "Treat numeric literals as normal free function symbols.",
    ),
    OptCell::new(
        EProverOption::FreeObjects,
        None,
        Some("free-objects"),
        OptArgType::NoArg,
        None,
        "Treat object identifiers as normal free function symbols.",
    ),
    OptCell::new(
        EProverOption::DefinitionalCnf,
        None,
        Some("definitional-cnf"),
        OptArgType::OptArg,
        Some("24"),
        "Set the formula definition introduction limit for clausification.",
    ),
    OptCell::new(
        EProverOption::FoolUnroll,
        None,
        Some("fool-unroll"),
        OptArgType::ReqArg,
        None,
        "Enable or disable FOOL unrolling.",
    ),
    OptCell::new(
        EProverOption::MiniscopeLimit,
        None,
        Some("miniscope-limit"),
        OptArgType::OptArg,
        Some("2147483648"),
        "Set the formula-size limit for miniscope transformations.",
    ),
    OptCell::new(
        EProverOption::PrintTypes,
        None,
        Some("print-types"),
        OptArgType::NoArg,
        None,
        "Print the type of every term.",
    ),
    OptCell::new(
        EProverOption::AppEncode,
        None,
        Some("app-encode"),
        OptArgType::NoArg,
        None,
        "Applicatively encode the proof state, print it, and exit.",
    ),
    OptCell::new(
        EProverOption::ArgCong,
        None,
        Some("arg-cong"),
        OptArgType::ReqArg,
        None,
        "Select ArgCong inference mode: all, max, or off.",
    ),
    OptCell::new(
        EProverOption::NegExt,
        None,
        Some("neg-ext"),
        OptArgType::ReqArg,
        None,
        "Select NegExt inference mode: all, max, or off.",
    ),
    OptCell::new(
        EProverOption::PosExt,
        None,
        Some("pos-ext"),
        OptArgType::ReqArg,
        None,
        "Select PosExt inference mode: all, max, or off.",
    ),
    OptCell::new(
        EProverOption::ExtSupMaxDepth,
        None,
        Some("ext-sup-max-depth"),
        OptArgType::ReqArg,
        None,
        "Set the maximal proof depth for Ext-family inferences.",
    ),
    OptCell::new(
        EProverOption::InverseRecognition,
        None,
        Some("inverse-recognition"),
        OptArgType::NoArg,
        None,
        "Enable recognition of injective function symbols.",
    ),
    OptCell::new(
        EProverOption::ReplaceInjDefs,
        None,
        Some("replace-inj-defs"),
        OptArgType::NoArg,
        None,
        "Replace injectivity definitions by inverse-function axioms after CNF.",
    ),
    OptCell::new(
        EProverOption::Bce,
        None,
        Some("bce"),
        OptArgType::ReqArg,
        None,
        "Enable or disable blocked clause elimination.",
    ),
    OptCell::new(
        EProverOption::BceMaxOccs,
        None,
        Some("bce-max-occs"),
        OptArgType::ReqArg,
        None,
        "Stop BCE symbol tracking after this many clause occurrences; -1 disables the limit.",
    ),
    OptCell::new(
        EProverOption::PredElim,
        None,
        Some("pred-elim"),
        OptArgType::ReqArg,
        None,
        "Enable or disable predicate elimination.",
    ),
    OptCell::new(
        EProverOption::PredElimRecognizeGates,
        None,
        Some("pred-elim-recognize-gates"),
        OptArgType::ReqArg,
        None,
        "Enable or disable gate recognition for predicate elimination.",
    ),
    OptCell::new(
        EProverOption::PredElimForceMuDecrease,
        None,
        Some("pred-elim-force-mu-decrease"),
        OptArgType::ReqArg,
        None,
        "Require predicate elimination to decrease the free-variable measure.",
    ),
    OptCell::new(
        EProverOption::PredElimIgnoreConjSyms,
        None,
        Some("pred-elim-ignore-conj-syms"),
        OptArgType::ReqArg,
        None,
        "Ignore conjecture symbols during predicate elimination.",
    ),
    OptCell::new(
        EProverOption::PredElimMaxOccs,
        None,
        Some("pred-elim-max-occs"),
        OptArgType::ReqArg,
        None,
        "Stop predicate-elimination symbol tracking after this many clause occurrences; -1 disables the limit.",
    ),
    OptCell::new(
        EProverOption::PredElimTolerance,
        None,
        Some("pred-elim-tolerance"),
        OptArgType::ReqArg,
        None,
        "Set the predicate-elimination measure tolerance.",
    ),
    OptCell::new(
        EProverOption::CnfLambdaToForall,
        None,
        Some("cnf-lambda-to-forall"),
        OptArgType::ReqArg,
        None,
        "Enable or disable conversion of lambda equations to quantified equations during CNF.",
    ),
    OptCell::new(
        EProverOption::EtaNormalize,
        None,
        Some("eta-normalize"),
        OptArgType::ReqArg,
        None,
        "Select eta normalization mode: reduce or expand.",
    ),
    OptCell::new(
        EProverOption::HoOrderKind,
        None,
        Some("ho-order-kind"),
        OptArgType::ReqArg,
        None,
        "Select higher-order ordering kind: lfho or lambda.",
    ),
    OptCell::new(
        EProverOption::EliminateLeibnizEq,
        None,
        Some("eliminate-leibniz-eq"),
        OptArgType::ReqArg,
        None,
        "Set the maximal proof depth for Leibniz equality elimination; -1 disables it.",
    ),
    OptCell::new(
        EProverOption::UnrollFormulasOnly,
        None,
        Some("unroll-formulas-only"),
        OptArgType::ReqArg,
        None,
        "Enable or disable recognizing only formulas as definitions during CNF.",
    ),
    OptCell::new(
        EProverOption::PrimEnumMode,
        None,
        Some("prim-enum-mode"),
        OptArgType::ReqArg,
        None,
        "Select primitive-enumeration mode.",
    ),
    OptCell::new(
        EProverOption::PrimEnumMaxDepth,
        None,
        Some("prim-enum-max-depth"),
        OptArgType::ReqArg,
        None,
        "Set the maximal proof depth for primitive enumeration; -1 disables it.",
    ),
    OptCell::new(
        EProverOption::InstChoiceMaxDepth,
        None,
        Some("inst-choice-max-depth"),
        OptArgType::ReqArg,
        None,
        "Set the maximal proof depth for defined-choice instantiation; -1 disables it.",
    ),
    OptCell::new(
        EProverOption::LocalRw,
        None,
        Some("local-rw"),
        OptArgType::ReqArg,
        None,
        "Enable or disable local rewriting.",
    ),
    OptCell::new(
        EProverOption::PruneArgs,
        None,
        Some("prune-args"),
        OptArgType::ReqArg,
        None,
        "Enable or disable pruning arguments of applied variables.",
    ),
    OptCell::new(
        EProverOption::FuncProjLimit,
        None,
        Some("func-proj-limit"),
        OptArgType::ReqArg,
        None,
        "Set the maximal number of functional projections.",
    ),
    OptCell::new(
        EProverOption::ImitLimit,
        None,
        Some("imit-limit"),
        OptArgType::ReqArg,
        None,
        "Set the maximal number of imitations.",
    ),
    OptCell::new(
        EProverOption::IdentLimit,
        None,
        Some("ident-limit"),
        OptArgType::ReqArg,
        None,
        "Set the maximal number of identifications.",
    ),
    OptCell::new(
        EProverOption::ElimLimit,
        None,
        Some("elim-limit"),
        OptArgType::ReqArg,
        None,
        "Set the maximal number of eliminations.",
    ),
    OptCell::new(
        EProverOption::UnifMode,
        None,
        Some("unif-mode"),
        OptArgType::ReqArg,
        None,
        "Select unification mode: single or multi.",
    ),
    OptCell::new(
        EProverOption::PatternOracle,
        None,
        Some("pattern-oracle"),
        OptArgType::ReqArg,
        None,
        "Enable or disable the pattern oracle.",
    ),
    OptCell::new(
        EProverOption::FixpointOracle,
        None,
        Some("fixpoint-oracle"),
        OptArgType::ReqArg,
        None,
        "Enable or disable the fixpoint oracle.",
    ),
    OptCell::new(
        EProverOption::MaxUnifiers,
        None,
        Some("max-unifiers"),
        OptArgType::ReqArg,
        None,
        "Set the maximal number of returned unifiers.",
    ),
    OptCell::new(
        EProverOption::MaxUnifSteps,
        None,
        Some("max-unif-steps"),
        OptArgType::ReqArg,
        None,
        "Set the maximal number of variable bindings in one unifier computation.",
    ),
    OptCell::new(
        EProverOption::ClassificationTimeoutPortion,
        None,
        Some("classification-timeout-portion"),
        OptArgType::ReqArg,
        None,
        "Set the percent of CPU time devoted to problem classification.",
    ),
    OptCell::new(
        EProverOption::PreinstantiateInduction,
        None,
        Some("preinstantiate-induction"),
        OptArgType::ReqArg,
        None,
        "Enable or disable induction-oriented preinstantiation.",
    ),
    OptCell::new(
        EProverOption::TermOrdering,
        Some('t'),
        Some("term-ordering"),
        OptArgType::ReqArg,
        None,
        "Select the term-ordering implementation.",
    ),
    OptCell::new(
        EProverOption::OrderWeightGeneration,
        Some('w'),
        Some("order-weight-generation"),
        OptArgType::ReqArg,
        None,
        "Select a method for generating term-ordering weights.",
    ),
    OptCell::new(
        EProverOption::OrderWeights,
        None,
        Some("order-weights"),
        OptArgType::ReqArg,
        None,
        "Provide partial term-ordering weight assignments.",
    ),
    OptCell::new(
        EProverOption::OrderPrecedenceGeneration,
        Some('G'),
        Some("order-precedence-generation"),
        OptArgType::ReqArg,
        None,
        "Select a method for generating a term-ordering precedence.",
    ),
    OptCell::new(
        EProverOption::PrecPureConj,
        None,
        Some("prec-pure-conj"),
        OptArgType::OptArg,
        Some("10"),
        "Set the precedence modifier for conjecture-only symbols.",
    ),
    OptCell::new(
        EProverOption::PrecConjAxiom,
        None,
        Some("prec-conj-axiom"),
        OptArgType::OptArg,
        Some("5"),
        "Set the precedence modifier for conjecture-and-axiom symbols.",
    ),
    OptCell::new(
        EProverOption::PrecPureAxiom,
        None,
        Some("prec-pure-axiom"),
        OptArgType::OptArg,
        Some("2"),
        "Set the precedence modifier for axiom-only symbols.",
    ),
    OptCell::new(
        EProverOption::PrecSkolem,
        None,
        Some("prec-skolem"),
        OptArgType::OptArg,
        Some("2"),
        "Set the precedence modifier for Skolem symbols.",
    ),
    OptCell::new(
        EProverOption::PrecDefPred,
        None,
        Some("prec-defpred"),
        OptArgType::OptArg,
        Some("2"),
        "Set the precedence modifier for introduced predicate symbols.",
    ),
    OptCell::new(
        EProverOption::OrderConstantWeight,
        Some('c'),
        Some("order-constant-weight"),
        OptArgType::ReqArg,
        None,
        "Set a positive special constant weight for the term ordering.",
    ),
    OptCell::new(
        EProverOption::Precedence,
        None,
        Some("precedence"),
        OptArgType::OptArg,
        Some(""),
        "Provide a partial term-ordering precedence.",
    ),
    OptCell::new(
        EProverOption::LpoRecursionLimit,
        None,
        Some("lpo-recursion-limit"),
        OptArgType::OptArg,
        Some("100"),
        "Set the recursion-depth limit for LPO comparisons.",
    ),
    OptCell::new(
        EProverOption::RestrictLiteralComparisons,
        None,
        Some("restrict-literal-comparisons"),
        OptArgType::NoArg,
        None,
        "Make literals incomparable in the term ordering.",
    ),
    OptCell::new(
        EProverOption::LiteralComparison,
        None,
        Some("literal-comparison"),
        OptArgType::ReqArg,
        None,
        "Select how literal comparisons use the term ordering.",
    ),
    OptCell::new(
        EProverOption::KboLambdaWeight,
        None,
        Some("kbo-lam-weight"),
        OptArgType::ReqArg,
        None,
        "Set the lambda-symbol weight in KBO.",
    ),
    OptCell::new(
        EProverOption::KboDbWeight,
        None,
        Some("kbo-db-weight"),
        OptArgType::ReqArg,
        None,
        "Set the De Bruijn-variable weight in KBO.",
    ),
    OptCell::new(
        EProverOption::DeterministicRewriteSort,
        None,
        Some("detsort-rw"),
        OptArgType::NoArg,
        None,
        "Sort clauses eliminated by backward rewriting using a total syntactic ordering.",
    ),
    OptCell::new(
        EProverOption::DeterministicNewSort,
        None,
        Some("detsort-new"),
        OptArgType::NoArg,
        None,
        "Sort newly generated and backward simplified clauses using a total syntactic ordering.",
    ),
];
