use crate::inout::commandline::{OptArgType, OptCell};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum EProverOption {
    Help,
    Version,
    Verbose,
    Output,
    Silent,
    OutputLevel,
    ProofObject,
    ProofGraph,
    ProofStatistics,
    FullDerivation,
    ForceDerivation,
    RecordGivenClauses,
    TrainingExamples,
    CpuLimit,
    SoftCpuLimit,
    MemoryLimit,
    SyntaxOnly,
    PrintFormulas,
    PruneOnly,
    CnfOnly,
    PrintPid,
    PrintVersion,
    RequireNonempty,
    Auto,
    DeterministicRewriteSort,
    DeterministicNewSort,
}

pub const EPROVER_OPTIONS: &[OptCell<EProverOption>] = &[
    OptCell::new(
        EProverOption::Help,
        Some('h'),
        Some("help"),
        OptArgType::NoArg,
        None,
        "Print a short description of program usage and options.",
    ),
    OptCell::new(
        EProverOption::Version,
        Some('V'),
        Some("version"),
        OptArgType::NoArg,
        None,
        "Print the version number of the prover. Please include this with all bug reports (if any).",
    ),
    OptCell::new(
        EProverOption::Verbose,
        Some('v'),
        Some("verbose"),
        OptArgType::OptArg,
        Some("1"),
        "Verbose comments on the progress of the program.",
    ),
    OptCell::new(
        EProverOption::Output,
        Some('o'),
        Some("output-file"),
        OptArgType::ReqArg,
        None,
        "Redirect output into the named file.",
    ),
    OptCell::new(
        EProverOption::Silent,
        Some('s'),
        Some("silent"),
        OptArgType::NoArg,
        None,
        "Equivalent to --output-level=0.",
    ),
    OptCell::new(
        EProverOption::OutputLevel,
        Some('l'),
        Some("output-level"),
        OptArgType::ReqArg,
        None,
        "Select an output level, greater values imply more verbose output.",
    ),
    OptCell::new(
        EProverOption::ProofObject,
        Some('p'),
        Some("proof-object"),
        OptArgType::OptArg,
        Some("1"),
        "Generate and print an internal proof object in case of success.",
    ),
    OptCell::new(
        EProverOption::ProofGraph,
        None,
        Some("proof-graph"),
        OptArgType::OptArg,
        Some("3"),
        "Generate an internal proof object as a GraphViz dot graph in case of success.",
    ),
    OptCell::new(
        EProverOption::ProofStatistics,
        None,
        Some("proof-statistics"),
        OptArgType::NoArg,
        None,
        "Print various statistics of the proof object.",
    ),
    OptCell::new(
        EProverOption::FullDerivation,
        Some('d'),
        Some("full-deriv"),
        OptArgType::NoArg,
        None,
        "Include all derived formulas and clauses in the proof object.",
    ),
    OptCell::new(
        EProverOption::ForceDerivation,
        None,
        Some("force-deriv"),
        OptArgType::OptArg,
        Some("1"),
        "Force output of the derivation in indeterminate cases.",
    ),
    OptCell::new(
        EProverOption::RecordGivenClauses,
        None,
        Some("record-gcs"),
        OptArgType::NoArg,
        None,
        "Record given-clause selection as separate pseudo-inferences.",
    ),
    OptCell::new(
        EProverOption::TrainingExamples,
        None,
        Some("training-examples"),
        OptArgType::OptArg,
        Some("1"),
        "Generate and process training examples from the proof-search object.",
    ),
    OptCell::new(
        EProverOption::MemoryLimit,
        Some('m'),
        Some("memory-limit"),
        OptArgType::ReqArg,
        None,
        "Limit the memory the prover may use. The argument is the allowed amount of memory in MB.",
    ),
    OptCell::new(
        EProverOption::CpuLimit,
        None,
        Some("cpu-limit"),
        OptArgType::OptArg,
        Some("300"),
        "Limit the per-core CPU time the prover should run.",
    ),
    OptCell::new(
        EProverOption::SoftCpuLimit,
        None,
        Some("soft-cpu-limit"),
        OptArgType::OptArg,
        Some("290"),
        "Limit the CPU time the prover should spend in the main saturation phase.",
    ),
    OptCell::new(
        EProverOption::SyntaxOnly,
        None,
        Some("syntax-only"),
        OptArgType::NoArg,
        None,
        "Stop after parsing, i.e. only check if the input can be parsed correctly.",
    ),
    OptCell::new(
        EProverOption::PrintFormulas,
        None,
        Some("print-formulas"),
        OptArgType::NoArg,
        None,
        "Print back an include-expanded formula-version of the problem after syntax checking.",
    ),
    OptCell::new(
        EProverOption::PruneOnly,
        None,
        Some("prune"),
        OptArgType::NoArg,
        None,
        "Stop after relevancy pruning and output the initial clause and formula set.",
    ),
    OptCell::new(
        EProverOption::CnfOnly,
        None,
        Some("cnf"),
        OptArgType::NoArg,
        None,
        "Convert the input problem into clause normal form and print it.",
    ),
    OptCell::new(
        EProverOption::PrintPid,
        None,
        Some("print-pid"),
        OptArgType::NoArg,
        None,
        "Print the process id of the prover as a comment after option processing.",
    ),
    OptCell::new(
        EProverOption::PrintVersion,
        None,
        Some("print-version"),
        OptArgType::NoArg,
        None,
        "Print the version number of the prover as a comment after option processing.",
    ),
    OptCell::new(
        EProverOption::RequireNonempty,
        None,
        Some("error-on-empty"),
        OptArgType::NoArg,
        None,
        "Return with an error code if the input file contains no clauses.",
    ),
    OptCell::new(
        EProverOption::Auto,
        None,
        Some("auto"),
        OptArgType::NoArg,
        None,
        "Automatically determine settings for proof search.",
    ),
    OptCell::new(
        EProverOption::DeterministicRewriteSort,
        None,
        Some("detsort-rw"),
        OptArgType::NoArg,
        None,
        "Sort clauses eliminated by backward rewriting using a total syntactic ordering.",
    ),
    OptCell::new(
        EProverOption::DeterministicNewSort,
        None,
        Some("detsort-new"),
        OptArgType::NoArg,
        None,
        "Sort newly generated and backward simplified clauses using a total syntactic ordering.",
    ),
];
