[package]
name = "umlaut"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-or-later"
publish = false

[features]
default = []
measure-expensive = []
measure-unification = []
instrument-perf-ctr = []
pdt-count-nodes = []
print-index-stats = []

[[bin]]
name = "umlaut"
path = "src/bin/umlaut.rs"

[[bin]]
name = "umlaut-csscpa-filter"
path = "src/bin/umlaut-csscpa-filter.rs"

[[bin]]
name = "umlaut-stratpar"
path = "src/bin/umlaut-stratpar.rs"

[[bin]]
name = "umlaut-ltb-runner"
path = "src/bin/umlaut-ltb-runner.rs"

[[bin]]
name = "umlaut-termprops"
path = "src/bin/umlaut-termprops.rs"

[[bin]]
name = "umlaut-term2dag"
path = "src/bin/umlaut-term2dag.rs"

[[bin]]
name = "umlaut-commandline-example"
path = "src/bin/umlaut-commandline-example.rs"

[[bin]]
name = "umlaut-pcl-extract"
path = "src/bin/umlaut-pcl-extract.rs"

[[bin]]
name = "umlaut-pcl-analyse"
path = "src/bin/umlaut-pcl-analyse.rs"

[[bin]]
name = "umlaut-checkproof"
path = "src/bin/umlaut-checkproof.rs"

[[bin]]
name = "umlaut-pcl-lemma"
path = "src/bin/umlaut-pcl-lemma.rs"

[[bin]]
name = "umlaut-dpll"
path = "src/bin/umlaut-dpll.rs"

[[bin]]
name = "umlaut-ground"
path = "src/bin/umlaut-ground.rs"

[[bin]]
name = "umlaut-classify-problem"
path = "src/bin/umlaut-classify-problem.rs"

[[bin]]
name = "umlaut-tsm-classify"
path = "src/bin/umlaut-tsm-classify.rs"

[[bin]]
name = "umlaut-direct-examples"
path = "src/bin/umlaut-direct-examples.rs"

[[bin]]
name = "umlaut-client"
path = "src/bin/umlaut-client.rs"

[[bin]]
name = "umlaut-deduction-server"
path = "src/bin/umlaut-deduction-server.rs"

[[bin]]
name = "umlaut-server"
path = "src/bin/umlaut-server.rs"

[[bin]]
name = "umlaut-axiom-filter"
path = "src/bin/umlaut-axiom-filter.rs"

[[bin]]
name = "umlaut-normalizer"
path = "src/bin/umlaut-normalizer.rs"

[[bin]]
name = "umlaut-patternize"
path = "src/bin/umlaut-patternize.rs"

[[bin]]
name = "umlaut-kb-create"
path = "src/bin/umlaut-kb-create.rs"

[[bin]]
name = "umlaut-kb-delete"
path = "src/bin/umlaut-kb-delete.rs"

[[bin]]
name = "umlaut-kb-insert"
path = "src/bin/umlaut-kb-insert.rs"

[[bin]]
name = "umlaut-kb-ginsert"
path = "src/bin/umlaut-kb-ginsert.rs"

[dependencies]

[profile.release]
codegen-units = 1
lto = "fat"
